nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
salario = float(input('Digite seu salário: '))
casado = bool(input('Casado True para sim False para não: '))
sexo = input('Digite seu sexo: ')

print(nome)
print(f'Sua idade é {idade}')
print(f'Sua idade daqui a 10 anos será {( idade + 10 )}')
print(salario)
print(casado)
print(sexo)
